import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../providers";
import { Grid, GridItem } from "@chakra-ui/react";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function YourFolderLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <Grid
        templateAreas={`"nav main"
                        "nav footer"`}
        gridTemplateRows={"100vh 1fr 0px"}
        gridTemplateColumns={"23vw 1fr"}
        h="100vh"
        color="blackAlpha.700"
        fontWeight="bold"
        className={inter.className}
      >
        <Navbar />
        <GridItem pl="2" bg="#31363F" area={"main"}>
          {children}
        </GridItem>
      </Grid>
    </Providers>
  );
}
