import { Providers } from "./providers";
import { Roboto_Mono } from "@next/font/google";

const font = Roboto_Mono({
  weight: ["400", "600", "700"], // Specify font weights
  subsets: ["latin"], // Load the latin subset (or others if needed)
  display: "swap", // Optional: to prevent layout shifts
});
export const metadata = {
  title: "Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
