import { Providers } from "../providers";

export const metadata = {
  title: "Portfolio guide",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Providers>{children}</Providers>;
}
